### ISSUE TITLE
[Windows][melodic] add Windows build support 

### ISSUE THREAD

**Issue by seanyen** [ros/kdl_parser#25]
This is an enhancement ticket for `kdl_parser`. I am using this ticket to track all the required work to bring up `kdl_parser` to be able to build & run on Windows/MSVC (which is verified in https://aka.ms/ros project). And hope the maintainers can take a look. Thanks!

- [x] (must-have) correct DEPRECATED helper macro #22
- [x] (must-have) update install destination in CMakeLists.txt  #23
- [x] (nice-have) update how c++11 requirement is added #24

**Comment by seanyen** [comment]
@clalancette @sloretz

**Comment by sloretz** [comment]
last bullet #24 is resolved, so I'll close this assuming there's nothing else
